[package]
name = "penumbra-view"
version = "0.1.0"
authors = ["Penumbra Labs <team@penumbra.zone>"]
edition = "2021"
description = "The view RPC library for the Penumbra Zone"
repository = "https://github.com/penumbra-zone/penumbra/"
homepage = "https://penumbra.zone"
license = "MIT OR Apache-2.0"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
# When this feature is enabled, the view worker will request every single
# NCT root, to pinpoint exactly where any NCT root divergence occurs.
nct-divergence-check = []

[dependencies]
# Workspace dependencies
penumbra-proto = { path = "../proto" }
penumbra-chain = { path = "../chain" }
penumbra-crypto = { path = "../crypto" }
penumbra-tct = { path = "../tct" }
penumbra-transaction = { path = "../transaction" }

sqlx = { version = "0.5", features = [ "runtime-tokio-rustls", "offline", "sqlite" ] }
tokio = { version = "1.16", features = ["full"]}
tokio-stream = { version =  "0.1.8", features = ["sync"] }
anyhow = "1"
directories = "4.0.1"
rand_core = { version = "0.6.3", features = ["getrandom"] }
rand = "0.8"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
serde_with = { version = "1.11", features = ["hex"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tonic = "0.6.1"
bincode = "1.3.3"
bytes = { version = "1", features = ["serde"] }
prost = "0.9"
futures = "0.3"
hex = "0.4"
metrics = "0.19.0"
async-stream = "0.2"
reqwest = { version = "0.11", features = ["json"] }
parking_lot = "0.12"
clap = { version = "3", features = ["derive"] }
camino = "1"

[build-dependencies]
vergen = "5"
